// Authentication
export const REQUEST_LOGIN = 'REQUEST_LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const REQUEST_LOGOUT = 'REQUEST_LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

// UI
export const TOGGLE_SNACKBAR = 'TOGGLE_SNACKBAR';
export const DISPLAY_LOADER = 'DISPLAY_LOADER';

// Site content
export const REQUEST_SITE_CONTENT = 'REQUEST_SITE_CONTENT';
export const REQUEST_SITE_CONTENT_SUCCESS = 'REQUEST_SITE_CONTENT_SUCCESS';
export const REQUEST_SITE_CONTENT_FAIL = 'REQUEST_SITE_CONTENT_FAIL';

