export const INCREMENT_VALUE = 'INCREMENT_VALUE';
export const DECREMENT_VALUE = 'DECREMENT_VALUE';

// MordorMarket actions
export const REQUEST_PRODUCTS = 'REQUEST_PRODUCTS';
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS';

export const REQUEST_USERS = 'REQUEST_USERS';
export const RECEIVE_USERS = 'RECEIVE_USERS';

export const BUY_PRODUCTS = 'BUY_PRODUCTS';

export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART';

export const HIDE_CONFIRMATION_MODAL = 'HIDE_CONFIRMATION_MODAL';
export const DISPLAY_CONFIRMATION_MODAL = 'DISPLAY_CONFIRMATION_MODAL';